### ISSUE TITLE
Get to route params

### ISSUE THREAD

**Issue by absemetov** [kimroen/ember-cli-document-title#18]
Like this:
``` javascript
titleToken: function(model, params) {
    return params.status_id;
}
```

**Comment by kimroen** [comment]
Not a bad idea, but you do have your route available as the context, so you could do something like this:

```js
titleToken() {
  return this.paramsFor(this.routeName).status_id;
}
```
On my phone so I didn't try this, but I believe it would work. Let me know!

**Comment by absemetov** [comment]
yes, this work
thanks
