### ISSUE TITLE
Title token using an async relationship

### ISSUE THREAD

**Issue by gzurbach** [kimroen/ember-cli-document-title#42]
Hi there! First off, thanks a lot for this great add-on. I've been using it for a while and just found out a (minor) issue.

I have a `models/foo.js` with an `async` relationship to a `user` such as:

```
export default DS.Model.extend({
  title: DS.attr('string'),
  user: DS.belongsTo('user', { async: true })
});
```

In my `routes/foo.js` I have the following `titleToken`:

```
export default Ember.Route.extend({
  titleToken(model) {
    return model.get('user.firstName');
  }
});
```

Because `user`is async, `user.firstName`is `undefined` at this point (`user` is still a `Promise`). When the promise is resolved, the title does not recompute so my title stays empty.

Would you have any recommendation about how to circumvent this issue? Thanks!

**Comment by blimmer** [comment]
It would be nice to add support for promises returned from the `titleToken` method. As a workaround, you could load the user as part of your model hook so it will be loaded when `titleToken` is called.

**Comment by gzurbach** [comment]
That did the trick, thanks!

**Comment by poohitan** [comment]
I've made a pull request to resolve this issue quite a long time ago, but it hasn't been reviewed and merged yet. It seems that this project is not being supported anymore :(

**Comment by kimroen** [comment]
> I've made a pull request to resolve this issue quite a long time ago, but it hasn't been reviewed and merged yet. It seems that this project is not being supported anymore :(

Sorry about that. I don't use Ember for work at the moment, so fitting in working on addons is a bit harder than it used to be.
