### ISSUE TITLE
Fastboot Support

### ISSUE THREAD

**Issue by rudymacias** [kimroen/ember-cli-document-title#43]
This add-on is mentioned to support Ember Fastboot apps but I'm unable to see it actually work as expected. It does work normally when EmberJS is loaded, but when viewing the site source contents, the title is the same as written in "app/index.html" file. As a Ember Fastboot app I would expect for the title tag to change based on the configuration set. If this is a Fastboot issue, please disregard my issue. Thanks!

**Comment by csheppard** [comment]
Yup my model hooks don't set the title for fastboot

**Comment by rudymacias** [comment]
@csheppard Hey so I was able to fix by doing the following:

1. Remove the `<title>` tag from the `app/index.html` file.
2. Add `<title>` tag to the `app/templates/head.hbs` file (of course placing the model title or the desired dynamic content).

And it worked out perfectly for me! Let me know if u need help.

**Comment by kellyselden** [comment]
@rudymacias I think you should reopen this. Your workaround of using another addon shouldn't be required.
