### ISSUE TITLE
Crash with Glimmer2 / Ember 2.9.0-alpha

### ISSUE THREAD

**Issue by workmanw** [kimroen/ember-cli-document-title#46]
Here is the stack:
```
on-error.js:77 Error: Property set failed: object in path "_dom.document" could not be found or was destroyed.
    at setPath (ember.debug.js:19288)
    at Object.set (ember.debug.js:19208)
    at Class.setTitle (document-title.js:85)
    at Class.collectTitleTokens (document-title.js:65)
    at Object.triggerEvent (ember.debug.js:26166)
    at Object.trigger (ember.debug.js:53740)
    at Object.trigger (ember.debug.js:52451)
    at Class.send (ember.debug.js:25514)
    at Class.updateTitle (document-title.js:77)
    at Object.applyStr (ember.debug.js:20768)
```

I believe the problem is that `container.lookup('renderer:-dom')` has changed it's structure and no longer has `_dom` on it. See:

With Ember 2.7:
<img width="523" alt="screen shot 2016-08-21 at 9 22 39 pm" src="https://cloud.githubusercontent.com/assets/825487/17841349/955a8b86-67e5-11e6-8c2c-2b09c48e96e5.png">

With Ember 2.9.0-alpha:
<img width="543" alt="screen shot 2016-08-21 at 9 23 16 pm" src="https://cloud.githubusercontent.com/assets/825487/17841352/9d48e9b4-67e5-11e6-896e-3b15b6561093.png">

I'll see if I can figure out a solution and submit a PR.

**Comment by awaer** [comment]
@kimroen can you review this so the addon will be ready for 2.9 stable in the coming weeks?

**Comment by kimroen** [comment]
@awaer Will do - thanks for checking in. https://github.com/kimroen/ember-cli-document-title/pull/49#issuecomment-251322501

**Comment by kimroen** [comment]
This is now released in `ember-cli-document-title@0.3.2` - thanks again 🎉

**Comment by workmanw** [comment]
Happy to help. 🎊

**Comment by kratiahuja** [comment]
This doesn't work with fastboot environment. I have a [PR](https://github.com/kimroen/ember-cli-document-title/pull/53) that fixes this correctly.
