### ISSUE TITLE
Broken on Ember 2.6(?)

### ISSUE THREAD

**Issue by kimroen** [kimroen/ember-cli-document-title#54]
From #53 

It [has been reported](https://github.com/kimroen/ember-cli-document-title/pull/53#issuecomment-261995564) that the latest release doesn't work on Ember 2.6. It [has also been reported](https://github.com/kimroen/ember-cli-document-title/pull/53#issuecomment-262066761) that it should, so we should figure that out.

**Comment by chriskrycho** [comment]
Figured out the issue; no problem here. We were setting up a mock router in an integration test (code smell!) and missed setting this up as well. Problem solved on our end by extracting routing back up to the controller level instead of this component. Feel free to close!

**Comment by kimroen** [comment]
That's great - thanks for letting me know!
