### ISSUE TITLE
Please release new version with Babel 6

### ISSUE THREAD

**Issue by danwenzel** [kimroen/ember-cli-document-title#63]
I notice that you have ember-cli-babel listed as version 6.x in master but not in the latest release. Could you please release a version with babel 6?

Thanks!

**Comment by josemarluedke** [comment]
Hello @kimroen. Could you release a new version containing the change to babel 6.x please?

Happy Holidays!

**Comment by The-Don-Himself** [comment]
Just another ping to add my voice to this.
New Year, New Version :)
@kimroen

**Comment by steveszc** [comment]
More info:
https://www.emberjs.com/blog/2017/11/20/ember-2-17-released.html#toc_changes-in-ember-cli-2-17

**Comment by thomblake** [comment]
@raido #67 claimed that it closes this issue, but it looks like npm doesn't have a new release for this yet. Can you publish a new version to npm?  Thanks!

**Comment by raido** [comment]
That is up to @kimroen :)

**Comment by Pezmc** [comment]
I'm also waiting for a new release to be cut! @kimroen!

**Comment by stephankaag** [comment]
👍

**Comment by kimroen** [comment]
Hi everyone! Happy holidays and New Year right back at you 🎉 

There is now a version of `ember-cli-document-title` that contains a fix for this issue - version `0.4.0`: https://github.com/kimroen/ember-cli-document-title/releases/tag/v0.4.0

Thank you for your patience ❤️

**Comment by Pezmc** [comment]
Thank you @kimroen!
