### ISSUE TITLE
Deprecation warning starting with Ember 3.1

### ISSUE THREAD

**Issue by Turbo87** [kimroen/ember-cli-document-title#71]
After updating to Ember 3.1 I've seen the following deprecation warning in our test suite logs:

> DEPRECATION: Route#router is an intimate API that has been renamed to Route#_router. However you might want to consider using the router service [deprecation id: ember-routing.route-router] See https://emberjs.com/deprecations/v3.x#toc_ember-routing-route-router for more details.

It appears to be related to the use of `self.router` at https://github.com/kimroen/ember-cli-document-title/blob/4c3d7c282c39bfc099ebf11a74be713809007691/vendor/document-title/document-title.js#L75

**Comment by btecu** [comment]
Possible fix #73.

**Comment by Kilowhisky** [comment]
And in fact it looks like they removed it.

https://github.com/emberjs/ember.js/pull/17134

Interesting as i thought they had to wait until ember 4 to remove stuff.

**Comment by Turbo87** [comment]
only for public APIs, private APIs can be removed whenever. this was considered "intimate" API so it got a deprecation warning and stayed around for a little longer.

**Comment by larryh** [comment]
Any updates forthcoming on this issue? I just upgraded to Ember 3.7.1 and ember-qunit 4.3.0. My app runs okay (albeit with an error message in the console), but this stops my tests dead in their tracks.

**Comment by bradmilburn** [comment]
f

**Comment by scottwernervt** [comment]
@mike-north made a fork https://github.com/mike-north/ember-cli-document-title-northm and I am currently using it in a project (eliminates the console warnings).
