### ISSUE TITLE
Incompatible with Ember 3.7?

### ISSUE THREAD

**Issue by lougreenwood** [kimroen/ember-cli-document-title#83]
Seems that the recent changes around the router service in Ember 3.7 breaks the add-on.

After upgrading I started to get this error:

```
Build Error (prember)

Cannot read property 'setTitle' of undefined
```

After digging through my node modules for `setTitle`, the only hit was this add-on.

**Comment by The-Don-Himself** [comment]
Yes, getting this too, from document-title.js line 75

**Comment by alexis89x** [comment]
Seems that from Ember 3.7.0 
`self.router.setTitle` should be changed into `self._router.setTitle`

**Comment by alexis89x** [comment]
Actually, it's this issue [#16312](https://github.com/emberjs/ember.js/pull/16312), included in Ember 3.1.0. From Ember 3.7.0, the deprecated self.router has been removed.

**Comment by scottwernervt** [comment]
@mike-north made a fork https://github.com/mike-north/ember-cli-document-title-northm and I am currently using it in a project (eliminates the console warnings). I recommend creating an issue or pull request there.

**Comment by Benjy1979** [comment]
Is this issue still present? I'm getting it after just installing it now.   self.router.setTitle(finalTitle); is crashing out.

**Comment by SparshithNR** [comment]
https://github.com/kimroen/ember-cli-document-title/blob/master/vendor/document-title/document-title.js#L73-L76
This change needs to be released. Code is merged, we need to cut a new version.
Changes made in #80

**Comment by snewcomer** [comment]
1.0 released!
